name: Docker, Build & Publish

on:
  workflow_call:
    secrets:
      CR_PAT:
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build the Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}/globalcart:${{ github.run_number }}-${{ github.sha::7 }} .
      - name: Push the Docker Image
        run: docker push ghcr.io/${{ github.repository }}/globalcart:${{ github.run_number }}-${{ github.sha::7 }}
